# NOTE: this toml config is a preset for 64 A100 GPUs.

[job]
dump_folder = "./outputs"
description = "Llama 3 8B training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 1
save_tb_folder = "tb"
enable_wandb = false

[model]
name = "llama3"
flavor = "1B"
hf_assets_path = "./assets/hf/Llama-3.2-1B"
# converters = ["float8"]

[optimizer]
name = "AdamW"
lr = 3e-4
eps = 1e-8

[lr_scheduler]
warmup_steps = 200  # lr scheduler warm up

[training]
local_batch_size = 1
seq_len = 2048
max_norm = 1.0  # grad norm clipping
steps = 4000
dataset = "c4"

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
pipeline_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable = true
last_save_in_hf = true
folder = "checkpoint"
interval = 100
last_save_model_only = true
export_dtype = "float32"
async_mode = "async" # ["disabled", "async", "async_with_pinned_mem"]

[compile]
enable=false
components = ["model", "loss"]

[activation_checkpoint]
mode = "none"  # ["none", "selective", "full"]
selective_ac_option = "op"  # "int" = ac every positive int layer or 'op', ac based on ops policy

[quantize.linear.float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
filter_fqns = ["output"]

[comm]
init_timeout_seconds = 3
train_timeout_seconds = 3

[validation]
enable = false
dataset = "c4_validation"
freq = 100
steps = 100
#steps = 1200 # Recommend value for c4_validation with world-size=8 and seq_len=8192
