# torchtitan Config.tomlsmoltrain

[experimental]
custom_args_module = "torchtitan.vlr.smolvlm.assets.job_config"

[job]
dump_folder = "./outputs_large"
description = "Llama 3 Siglip2 VLM training"
print_args = false

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 50
enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 1
disable_color_printing = false
enable_tensorboard = false
save_tb_folder = "tb"
enable_wandb = true

[model]
name = "llama3-siglip2"
flavor = "256M"
# test folder with tokenizer.json, for debug purpose only
# hf_assets_path = "torchtitan/experiments/vlm/assets/tokenizer"
hf_assets_path = "./assets/hf/SmolLM2-360M-Instruct"
# converters = ["float8"]

[optimizer]
name = "AdamW"
lr = 1e-5
eps = 1e-8

[lr_scheduler]
warmup_steps = 0  # lr scheduler warm up, normally 20% of the train steps
#decay_ratio = None  # lr scheduler decay ratio, 80% of the train steps
decay_type = "cosine"
min_lr_factor = 0.0

[training]
local_batch_size = 9
seq_len = 2048
# packing_buffer_size = 100
max_norm = 1.0  # grad norm clipping
steps = 13100
dataset = "finevision"
#dataset = "cc12m"

[comm]
init_timeout_seconds = 1
train_timeout_seconds = 1
save_traces_folder = "comm_traces"

[compile]
enable = false

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
fsdp_reshard_after_forward = "default" # default / never / always
tensor_parallel_degree = 1
enable_async_tensor_parallel = false
pipeline_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable = true
folder = "checkpoint"
interval = 50
last_save_model_only = false
#initial_load_in_hf = true
#last_save_in_hf = true
export_dtype = "bfloat16"
async_mode = "async"  # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = "selective"  # ["none", "selective", "full"]
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy
