name: 8 GPU Integration Test at H100

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
concurrency:
  group: unit-test${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  build-test:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: linux.rocm.gpu.mi300.8
      gpu-arch-type: rocm
      gpu-arch-version: "6.4"
      # This image is faster to clone than the default, but it lacks CC needed by triton
      # (1m25s vs 2m37s).
      docker-image: torchtitan-rocm-pytorch-nightly-ubuntu-22.04-clang19-py3
      repository: pytorch/torchtitan
      upload-artifact: outputs
      script: |
        set -eux

        USE_CPP=0 python -m pip install --pre torchao

        mkdir artifacts-to-be-uploaded
        python ./tests/integration_tests_h100.py artifacts-to-be-uploaded --ngpu 8

